version: "3.7"

services:

  discovery-server:
    container_name: discovery-server
    image: cebrailkaya/discovery-server:latest
    pull_policy: always
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_FETCH_REGISTRY: false
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: false
      spring.zipkin.base-url: http://zipkin:9411


  api-gateway:
    container_name: api-gateway
    image: cebrailkaya/api-gateway:latest
    pull_policy: always
    ports:
      - "8080:8080"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka
      spring.zipkin.base-url: http://zipkin:9411

    depends_on:
      - discovery-server
      - auth-service
      - zipkin



  auth-service:
    container_name: auth-service
    image: cebrailkaya/authentication:latest
    pull_policy: always
    ports:
      - "8081:8081"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/toyota
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 963258741
      spring.zipkin.base-url: http://zipkin:9411
    depends_on:
      - discovery-server



  product-service:
    container_name: product-service
    image: cebrailkaya/product-service:latest
    pull_policy: always
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/toyota
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 963258741
      spring.zipkin.base-url: http://zipkin:9411




  report-service:
    container_name: report-service
    image: cebrailkaya/report-service:latest
    pull_policy: always
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/toyota
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 963258741
      spring.zipkin.base-url: http://zipkin:9411




  sale-service:
    container_name: sale-service
    image: cebrailkaya/sale-service:latest
    pull_policy: always
    ports:
      - "8084:8084"
    depends_on:
      - discovery-server

    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/toyota
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 963258741
      spring.zipkin.base-url: http://zipkin:9411



  user-service:
    container_name: user-service
    image: cebrailkaya/user-service:latest
    pull_policy: always
    ports:
      - "8085:8085"
    depends_on:
      - discovery-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/toyota
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 963258741
      spring.zipkin.base-url: http://zipkin:9411

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"


